### ISSUE TITLE
MCMC for 2-factor MIRT/Ising

### ISSUE THREAD

**Issue by danielnjoo** [alexanderrobitzsch/sirt#1]
Hi Prof Robitzsch,

First this definitely isn't an issue with the package, but more of a general question... I'm working on a class project that involves MCMC methods for estimation in the Ising/2-factor MIRT model, and I came across your package as a result. 

My question is (1) what MCMC method your `2pno()` function uses,  (2) how might one use the  output from `2pno()`to create a graph in `qgraph`, and (3) do  you  know how to extend MCMC to a 2-factor MIRT model?

Thanks so much! Very new to the psychometrics field...

**Comment by alexanderrobitzsch** [comment]
Am 26.04.2018 um 21:40 schrieb danielnjoo:
> Hi Prof Robitzsch,
> 
> First this definitely isn't an issue with the package, but more of a
> general question... I'm working on a class project that involves MCMC
> methods for estimation in the Ising/2-factor MIRT model, and I came
> across your package as a result.
> 
> My question is (1) what MCMC method your `2pno()` function uses,

MCMC based on Gibbs sampling for all parameters (coded in pure R).

   (2)
> how might one use the  output from `2pno()`to create a graph in
> `qgraph`, and (3) is a  2-factor MIRT the same as a 2PNO?

No, "2PNO" is a unidimensional IRT model and the "2" refers to two item 
parameters: item intercept and item slope.

Best,
Alexander
