### ISSUE TITLE
issues with multidimensional rasch.mirtlc and "MLC2" 

### ISSUE THREAD

**Issue by andreanorcinipala** [alexanderrobitzsch/sirt#10]
Hi,
I keep getting this error when I run rasch.mirtlc with MLC2 and more than 1 dimension. 
I tried with your syntax:
mod33 <- sirt::rasch.mirtlc( dat, dimensions=dimensions, theta.k=theta.k, modeltype="MLC2")

but I keep getting the same error.
Error in r.jk[, , gg] * log(pjk.M) : non-conformable arrays
Thanks,
Andrea

**Comment by alexanderrobitzsch** [comment]
Should have been fixed in the recent dev version.
