### ISSUE TITLE
DETECT outcomes are inconsistent with the original DETECT software

### ISSUE THREAD

**Issue by czopluoglu** [alexanderrobitzsch/sirt#13]
Hi, 

I just emailed you but then realize there is a github repository for the package. So, I thought it would be more efficient to put this here as well.

I am struggling to reproduce the results. I compare the DETECT output from my previous research (using the original software) by analyzing the same dataset using the sirt package, and the results were quite different. Also, I analyzed the TIMSS data using the original DETECT program, and again the results were different. I attached the DETECT output from the original software using the same TIMSS dataset available in your package.

[detect.txt](https://github.com/alexanderrobitzsch/sirt/files/5134278/detect.txt)

I copied the R syntax I used below (same as in your example, the only difference is that I am using the sum scores for conditioning). 

```
data(data.timss)
dat <- data.timss$data
dat <- dat[, substring( colnames(dat),1,1)=="M" ]
iteminfo <- data.timss$item

a <- conf.detect(data=dat,
            score=rowSums(dat),
            itemcluster=iteminfo$Content.Domain)

summary(a)

-----------------------------------------------------------------
sirt 3.9-4 (2020-02-17 12:57:09)
R version 4.0.2 (2020-06-22) x86_64, mingw32 | nodename=COE-L-102R-WL01 | login=cengiz

Call:
conf.detect(data = dat, score = rowSums(dat), itemcluster = iteminfo$Content.Domain)

Confirmatory DETECT Analysis with 3 Item Clusters
Bandwidth Scale: 1.1
-----------------------------------------------------------------
Dimensionality Statistics
          unweighted weighted
DETECT         0.311    0.311
ASSI           0.273    0.273
RATIO          0.350    0.350
MADCOV100      0.888    0.888
MCOV100       -0.551   -0.551

```
As you can see the statistics are different. This is just an example for a confirmatory DETECT for the dataset available in your package. I did also try different datasets I have. The results are always (substantially) different for both confirmatory and exploratory DETECT procedure.

I understand that there may be nuances in algorithms used; however, these differences are not something we can ignore. Having these in R is great and provides a number of opportunities for research and make it easy to teach. On the other hand, before I use these functions for my research and recommend it to my students, I wonder if you have any insights about why the results are different, or what adjustments (if possible) to make so the results from R function is similar to the ones we get from the original DETECT program.

Thank you so much for your time and effort in developing this package.

**Comment by alexanderrobitzsch** [comment]
The difference is due to the way of how the DETECT index is computed. When a sum score is used, there is a bias correction proposal in Zhang and Stout (1999). This approach is now also available using the newly introduced argument ``use_sum_score=TRUE``. For the example dataset, I now obtain close results using the recent dev version ``sirt 3.10-64``.

**Comment by czopluoglu** [comment]
Thank you. However, I still don't get it. I installed the new dev version, and run the code for TIMSS data in your package. Here is the output.

```
data(data.timss)
dat <- data.timss$data
dat <- dat[, substring( colnames(dat),1,1)=="M" ]
iteminfo <- data.timss$item

a <- conf.detect(data=dat, 
            score=rowSums(dat),
            itemcluster=iteminfo$Content.Domain,
            use_sum_score=TRUE)

summary(a)
-----------------------------------------------------------------
sirt 3.10-64 (2020-08-29 14:27:25) 
R version 4.0.2 (2020-06-22) x86_64, mingw32 | nodename=COE-L-102R-WL01 | login=cengiz 

Call:
conf.detect(data = dat, score = rowSums(dat), itemcluster = iteminfo$Content.Domain, 
    use_sum_score = TRUE)

Confirmatory DETECT Analysis with 3 Item Clusters 
Bandwidth Scale: 1.1 
-----------------------------------------------------------------
Dimensionality Statistics 
          unweighted weighted
DETECT         0.742    0.742
ASSI           0.207    0.207
RATIO          0.259    0.259
MADCOV100      2.870    2.870
MCOV100       -2.862   -2.862

```
Now, it reports a DETECT value of 0.742. The original software reports a DETECT value of 0.188.

What am I missing?

**Comment by alexanderrobitzsch** [comment]
This is surprising. With my local version, I got 0.187. I check this again.

**Comment by alexanderrobitzsch** [comment]
I just checked the results with a recent version which I installed from the Github version. 

I used the code

```
data(data.timss)
dat <- data.timss$data
dat <- dat[, substring( colnames(dat),1,1)=="M" ]
iteminfo <- data.timss$item

mod2 <- conf.detect(data=dat, use_sum_score=TRUE,
            score=rowSums(dat), smooth=FALSE,
            itemcluster=iteminfo$Content.Domain)

summary(mod2)
```

I received

```
sirt 3.10-64 (2020-08-29 14:27:25) 
R version 4.0.0 (2020-04-24) x86_64, mingw32 | nodename=IPN077126 | login=sunpn563 

Call:
conf.detect(data = dat, score = rowSums(dat), itemcluster = iteminfo$Content.Domain, 
    smooth = FALSE, use_sum_score = TRUE)

Confirmatory DETECT Analysis with 3 Item Clusters 
Bandwidth Scale: 1.1 

Dimensionality Statistics 
          unweighted weighted
DETECT         0.187    0.187
ASSI           0.100    0.100
RATIO          0.252    0.252
MADCOV100      0.742    0.742
MCOV100        0.014    0.014
```

The value ``0.187`` is reproduced. I do not know why differences occur.

**Comment by czopluoglu** [comment]
yes, right! I didn't have `smooth=FALSE` argument. When I added that argument, it know produces the identical numbers. It is interesting how much impact it has.

I also verified it with a different dataset and got identical results.

Thank you again. Now, we at least know how we can reproduce the results identical to the original program.

```
smooth=FALSE
use_sum_score=TRUE
```
