### ISSUE TITLE
DETECT Exploratory analysis

### ISSUE THREAD

**Issue by czopluoglu** [alexanderrobitzsch/sirt#14]
Hi,

In the explaratory analysis, it seems that the function does cross-validation no matter what the user does. It has an argument N.est which the user can specify the sample size for splitting the data if cross-validation is wanted. However, we should be able to run the exploratory procedure without cross-validation using the full sample (as something possible in the original software).

I was expecting this behavior from the function when I set the `N.est=NULL` which is the default setting. It seems, the function just does a 50-50 split and runs cross-validation although we set `N.est=NULL`.

Can you check this? Would you be able allow the user to run the exploratory procedure with the full sample without cross-validation when `N.est=NULL`?

I put below the example from the package.

```

data(data.timss)
dat <- data.timss$data
dat <- dat[, substring( colnames(dat),1,1)=="M" ]
iteminfo <- data.timss$item

expl.detect(data      = dat, 
            score     = rowSums(dat), 
            nclusters = 2,
            bwscale   = 1.1,
            N.est     = NULL,
            seed      = NULL,
            use_sum_score=TRUE)
```
Output indicates that the function automatically made a 50-50 split (N.est = 172, N.val=173). 

```
DETECT (unweighted)

Optimal Cluster Size is  2  (Maximum of DETECT Index)

  N.Cluster N.items N.est N.val size.cluster DETECT.est ASSI.est RATIO.est
1         2      25   172   173        15-10        0.3     0.04     0.119
  MADCOV100.est MCOV100.est DETECT.val ASSI.val RATIO.val MADCOV100.val
1         2.522      -2.493      0.092    0.027     0.036         2.542
  MCOV100.val
1      -2.521
$detect.unweighted
    DETECT.val   ASSI.val  RATIO.val MADCOV100.val MCOV100.val
Cl2 0.09231698 0.02666667 0.03631547      2.542084   -2.520976

$detect.weighted
    DETECT.val   ASSI.val  RATIO.val MADCOV100.val MCOV100.val
Cl2 0.09231698 0.02666667 0.03631547      2.542084   -2.520976

```

Thank you.

**Comment by alexanderrobitzsch** [comment]
One can choose ``N.est=N`` where ``N`` is the original sample size. Then, no validation is perfomed.

**Comment by czopluoglu** [comment]
Great! Thank you. It seems obvious, but couldn't think about it.
