### ISSUE TITLE
using btm function with eps = 0 returns error

### ISSUE THREAD

**Issue by SanVerhavert** [alexanderrobitzsch/sirt#2]
Executing the following line of code (with data from [data.txt](https://github.com/alexanderrobitzsch/sirt/files/2097568/data.txt)  with specs: sep = ";", dec = "." )
`Ability_sirt <- btm( data = Data, fix.eta = 0, fix.delta = 0, eps = 0 )`
returns the error and warning
```
Error in while ((iter < maxiter) & (max.change > conv)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In max(theta_ch, na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
```

The problem is located in the file btm.r on [line 62](https://github.com/alexanderrobitzsch/sirt/blob/027c25ee3fd8ca3658c4a808ad8c781422a4974b/R/btm.R#L62). Calculating the mean of a vector containing INF values results in an INF value. If there is no epsilon correction (i.e. `eps = 0`) [line 60](https://github.com/alexanderrobitzsch/sirt/blob/027c25ee3fd8ca3658c4a808ad8c781422a4974b/R/btm.R#L60) produces an -INF value (in the example data) because there is a 0 score.

A possible solution, in my opinion, is  to insert the block from [line 65 to line 76](https://github.com/alexanderrobitzsch/sirt/blob/027c25ee3fd8ca3658c4a808ad8c781422a4974b/R/btm.R#L65-L76) between [line 60 and 61](https://github.com/alexanderrobitzsch/sirt/blob/027c25ee3fd8ca3658c4a808ad8c781422a4974b/R/btm.R#L60-L61) and add the line of code `theta[elim_persons_index] <- NA` after the line `theta_elim <- theta[ elim_persons_index ]` in the moved block.

That part of code should look as follows
```
theta <- 0.8 * stats::qlogis(propscore)
elim_persons <- FALSE
if (sum(propscore %in% c(0, 1)) > 0) {
  elim_persons <- TRUE
  elim_persons_index <- which(propscore %in% c(0, 1))
  theta_elim <- theta[elim_persons_index]
  theta[elim_persons_index] <- NA
  indicator_elim <- dat0
  indicator_elim[, 3] <- 0
  indicator_elim[indicator_elim[, 1] %in% elim_persons_index, 
                 3] <- 1
  indicator_elim[indicator_elim[, 2] %in% elim_persons_index, 
                 3] <- 1
}
if (center.theta) {
  theta <- theta - mean(theta, na.rm = T )
}
some.fixed.theta <- FALSE
```

[data.txt](https://github.com/alexanderrobitzsch/sirt/files/2097568/data.txt)

**Comment by alexanderrobitzsch** [comment]
I decided to replace the line for calculating initial values by `theta <- stats::qlogis( ( propscore + .1 ) / 1.2 )` which avoids inifinite estimates. I submitted a new package version on Github.

**Comment by SanVerhavert** [comment]
That is indeed a more elegant solution.
I am unfornunately unable to test the change myself because the `devtools::install_github( "alexanderrobitzsch/sirt" )` cannot install the package and returns the following output (last 8 lines)
```
init.o:init.c:(.text+0x0): multiple definition of `R_init_sirt'
RcppExports.o:RcppExports.cpp:(.text+0x1f0): first defined here
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'sirt'
* removing 'C:/Users/SVerhavert/Documents/R/win-library/3.5/sirt'
In R CMD INSTALL
Installation failed: Command failed (1)
```

**Comment by alexanderrobitzsch** [comment]
Yes, I agree. This was an incorrect version. I just updated a new version in which the problem should have been solved.

**Comment by SanVerhavert** [comment]
The change works fine! Thanks!
