### ISSUE TITLE
invariance.alignment - Ordered categorical data (item threshold parameters)

### ISSUE THREAD

**Issue by MitjaCernko** [alexanderrobitzsch/sirt#26]
First of all, thank you for the wonderful work of making the alignment procedure more accessible within R!

I'm wondering how difficult would it be to implement the option to include item thresholds as parameters in addition to the item intercepts (relevant in the case of ordered categorical CFA)?

If not, any pointers as to how you would approach this would be greatly appreciated - the "Alignment" function from the "AlignLV" package supports this option, and it seems like a useful starting point...

**Comment by alexanderrobitzsch** [comment]
The thresholds can be defined as item intercepts and item loadings have just to be duplicated according to the number of thresholds per item.

**Comment by MitjaCernko** [comment]
Thank you very much!
