### ISSUE TITLE
comparing rasch.jml to winsteps

### ISSUE THREAD

**Issue by thoughtafter** [alexanderrobitzsch/sirt#3]
I'm developing software for a client who want IRT item difficulties to match Winsteps. My understanding is that Winsteps centers item difficulty at 0. Is there a way to use `rasch.jml` to get numbers similar to Winsteps?

**Comment by alexanderrobitzsch** [comment]
I added the argument `center` in the `rasch.jml()` function. It is included in the dev version `sirt 3.0-12`.
