### ISSUE TITLE
gamma.testlet

### ISSUE THREAD

**Issue by volokhonsky** [alexanderrobitzsch/sirt#4]
Hi! 
Thank you for your efforts!
Is there some reason to not include the gamma.testlet vector to the results of the `mcmc.3pno.testlet` function?

**Comment by alexanderrobitzsch** [comment]
There is no particular reason. I included the argument `save.gamma.testlet` in the `sirt::mcmc.3pno.testlet()` function in `sirt 3.0-14` which now allows one to save `gamma.testlet` sampled values.
