### ISSUE TITLE
rasch.jml. itemdiff.correction incorrect when using constraints

### ISSUE THREAD

**Issue by thoughtafter** [alexanderrobitzsch/sirt#6]
Presumably when using constraints the final values of itemdiff and itemdiff.correction should be equal to the constraint value. Using tam.jml with xsi.fixed and bias=TRUE and bias=FALSE the xsi values always match the xsi.fixed. We expect the same of `sirt::rasch.jml` for itemdiff and itemdiff.correction to match constraints.

**Comment by alexanderrobitzsch** [comment]
Changed in `sirt 3.0-30`.
