### ISSUE TITLE
modifying mcmc.3pno.testlet to make it 3pl model

### ISSUE THREAD

**Issue by hemanthboddu** [alexanderrobitzsch/sirt#7]
Hi Prof.Robitzsch,
What all changes need to be made to ``mcmc.3pno.testlet`` to make it a logistic testlet model? One would be to change the link function from pnorm to plogis in #draw latent responses Z (mcmc.3pno.testlet_alg.R). I guess the conditional distribution from which parameters are drawn would change but I don't know how. Can you point to the literature from which you coded MCMC Gibbs Sampler? Do you have plans to publish 3pl model for testlets?

**Comment by alexanderrobitzsch** [comment]
As stated in the manual, I used the MCMC algorithm of Glas (2012):

Glas, C. A. W. (2012). Estimating and testing the extended testlet model. LSAC Research Report Series, RR 12-03. 

There is some literature for Gibbs sampling of IRT models with the logistic link function, see

Jiang, Z., & Templin, J. (2018). Gibbs Samplers for Logistic Item Response Models via the Pólya–Gamma Distribution: A Computationally Efficient Data-Augmentation Strategy. Psychometrika, 1-17.  https://doi.org/10.1007/s11336-018-9641-x

Using a Metropolis-Hastings sampler would be always an alternative which has been applied in a dozen of papers.
