### ISSUE TITLE
TIBBLES ARE NO DATA FRAMES |  lsem.estimate(): error when input is tibble data frame

### ISSUE THREAD

**Issue by Deleetdk** [alexanderrobitzsch/sirt#9]
If one inputs a tibble data frame, one gets a very cryptic error about data types:

```
> admixture <- lsem.estimate(
+   data = d %>% filter(!is.na(EUR)) %>% as_tibble(),
+   moderator = "EUR",
+   moderator.grid = (0.18:0.76),
+   lavmodel = tcpg.model,
+   h = 2,
+   meanstructure = TRUE,
+   residualize = FALSE,
+   standardized = TRUE
+ )
Error in is.data.frame(x) : 
  (list) object cannot be coerced to type 'double'
```

The bug is in the sub-call to `sirt:::lsem_residualize()`, because this relies on an implicit conversion that doesn't happen with tibbles:

```
> sirt:::lsem_residualize
function (data, moderator, moderator.grid, lavmodel, h = 1.1, 
    residualize = TRUE, eps = 1e-10, verbose = TRUE) 
{
    lavaanstr <- lavaan::lavaanify(lavmodel)
    vars <- unique(c(lavaanstr$rhs, lavaanstr$lhs))
    vars <- intersect(colnames(data), vars)
    data.mod <- data[, moderator]
    res <- lsem_local_weights(data.mod = data.mod, moderator.grid = moderator.grid, 
        h = h)
```

The line `data[, moderator]` returns a vector if it's a standard data frame but a data frame if it's a tibble, hence the data type error when `lsem_local_weights()` is called and tries to convert. It's a simple fix, just change it to `data[[moderator]]`.

**Comment by alexanderrobitzsch** [comment]
Same issue with the input of ``moderator.grid``. Moreover, if it is really a problem of a tibble (I do not think so), then I am not willing to fix because I would expect that tibble's should behave as data frames. Otherwise, every R user can invent its own data format and could complain that functions are not working ... :-)

**Comment by Deleetdk** [comment]
Tibbles are the most commonly used non-standard data frame. They are part of the **tidyverse** meta-package, so you should support their use, or at least throw informative errors.

**Comment by alexanderrobitzsch** [comment]
No, I am not willing to support tidyverse objects.

**Comment by Deleetdk** [comment]
Why don't you just add a simple call `as.data.frame(x)` in the function initially to force the conversion to standard data frame? This prevents future users from getting uninformative errors. Pretty strange for a CRAN developer to note categorically they don't want to support **tidyverse** and refuse to implement a 5 second fix...

**Comment by alexanderrobitzsch** [comment]
Beacuse I would expect that a tibble is of class ``data.frame``. I would like to ask you to respect someone's to freedom to have the opinion that R does not need the tidyverse stuff. If people have different opinions on this topic, why not. In the manual it is stated, input a data frame. So, what is the question.

**Comment by Deleetdk** [comment]
A tibble is of class `data.frame`, yes:

```
> iris %>% as_tibble() %>% class()
[1] "tbl_df"     "tbl"        "data.frame"
> iris %>% class()
[1] "data.frame"
> iris %>% as_tibble() %>% as.data.frame() %>% class()
[1] "data.frame"
```

However, calling `as.data.frame()` still coerces to standard data frame. The solution here is trivial: you add this initial line: `data = as.data.frame(data)` and you're done.

**Comment by alexanderrobitzsch** [comment]
I agree that it is simple. But I do not like to include new lines of code because tibble's are not working as expected. Then, the issue lies in the definition of tibbles and I do not like to adapt my code due to conventions of tidyverse. Nevertheless (for other reasons), the conversion to a data frame could make sense, I agree.

**Comment by alexanderrobitzsch** [comment]
Included your suggestion in the code.

**Comment by alexanderrobitzsch** [comment]
The reason of incongruency is the different handling of dropping matrix dimensions between data frames and tibbles. If ``data`` is a data frame, the command ``data[,moderator]`` provides a vector and not a 1-column matrix. Essentially it uses ``data[,moderator, drop=TRUE]``. If ``data`` is a tibble, then the default is ``data[,moderator, drop=FALSE]``. I understand the rationale for setting ``drop=FALSE`` as a default, however, this comes with the consequence that tibbles does not work like data frames and break functions. If one wants to work with tibbles, then it is responsibility of the user to accept the inexpected behavior and not to request rewriting existing code.

**Comment by alexanderrobitzsch** [comment]
I would like to add a quote by Norman Matloff. I fully agree with this opinion and think that it is useful to add here in the discussion.

[https://github.com/matloff/TidyverseSkeptic/blob/master/READMEFull.md](https://github.com/matloff/TidyverseSkeptic/blob/master/READMEFull.md)

**[...] R is rapidly devolving into two mutually unintelligible dialects, ordinary R and the Tidyverse. Sadly, this is a conscious effort by a commercial entity that has come to dominate the R world, RStudio. I know and admire the people at RStudio, but a commercial entity should not have such undue influence on an open-source project.

It might be more acceptable if the Tidyverse were superior to ordinary R, but in my opinion it is not. It makes things more difficult for beginners. E.g. the Tidyverse has so many functions, some complex, that must be learned to do what are very simple operations in base R. Pipes, apparently meant to help beginners learn R, actually make it more difficult, I believe. And the Tidyverse is of questionable value for advanced users.**

**Comment by Deleetdk** [comment]
You are not helping your package grow with this irrational defiant behavior. I suggest you evaluate and simply add a check for tibble input. It takes only a few minutes. I can submit a PR if you like. Also, it is factually incorrect, as tibbles are data.frames class.

**Comment by alexanderrobitzsch** [comment]
To reiterate: If tibbles would act like data frames, they would not break my function. They are also of class data.frame. However, some defaults for tibbles are different than data.frames. In any case, I added the conversion to data.frames. My complaint was just that there is almost a parallel universe in R created by Hadley Wickham. I do not see that this framework is helpful for practical data analysis and creates issues for existing solutions. I fully understand that others have different opinions, but one cannot expect that all R users make functions compatible to tidyverse. I think that it should work the other way: tidyverse should be compatible to base R.
